spring:
  application:
    name: loan-approval
  data:
    mongodb:
      uri: mongodb://loan-approval:loan-approval@localhost:27017/loan-approval
workerId: blueprint
vanillabp:
  cockpit:
    rest:
      base-url: http://localhost:8079
      authentication:
        basic: true
        username: abc
        password: 123
    template-loader-path: classpath*:cockpit-templates/
    jwt:
      hmacSHA256-base64: 4FTHgU8uHPy/ahy8IhXHj/K/BVlh7snSUtf3m1XWLkg=
