spring:
    application:
        name: standalone-businesscockpit
    datasource:
        url: jdbc:h2:mem:testdb
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        show-sql: false
    h2:
        console:
            enabled: true #pfad + username pw
    data:
        mongodb:
            uri: mongodb:business-cockpit-mongo:27017

vanillabp:
    cockpit:
        rest:
            log: true
            base-url: http://localhost:9080/bpms/api/v1
            authentication:
                basic: true
                username: abc
                password: 123
        template-loader-path: classpath*:cockpit-templates/
        jwt:
            hmacSHA256-base64: oNr5wqOE2LBh5uKKVfTwubPfyF237OrffQj5bcMKtpw=

workerId: blueprint
