spring:
  application:
    name: loan-approval
  datasource:
    url: jdbc:h2:mem:blueprintdb
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          format_sql: true
      show-sql: false
  h2:
    console:
      enabled: true
workerId: blueprint
vanillabp:
  cockpit:
    rest:
      base-url: http://localhost:8079
      authentication:
        basic: true
        username: abc
        password: 123
    template-loader-path: classpath*:cockpit-templates/
    jwt:
      hmacSHA256-base64: 4FTHgU8uHPy/ahy8IhXHj/K/BVlh7snSUtf3m1XWLkg=
